name: Build Image Test

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
          VERSION=latest
        fi
        echo ::set-output name=VERSION::${VERSION}
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:master
    - name: Build docker image
      id: acr_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        build-args: |
          GITVERSION=git-${{ steps.vars.outputs.git_revision }}
          VERSION=${{ steps.get_version.outputs.VERSION }}
        tags: |-
          acr.kubevela.net/oamdev/velaux:${{ steps.get_version.outputs.VERSION }}
          oamdev/velaux:${{ steps.get_version.outputs.VERSION }}
